In [13]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census

# Census API Key
#from config import api_key
api_key = "ae22894202630756231cd41ab32697645054e407"
c = Census(api_key, year=2019)

In [14]:
# Run Census Search to retrieve data on all zip codes (2013 ACS5 Census)
# See: https://github.com/CommerceDataService/census-wrapper for library documentation
# See: https://gist.github.com/afhaque/60558290d6efd892351c4b64e5c01e9b for labels
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E",
                          "B17001_002E"), {'for': 'zip code tabulation area:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})

# Add in Poverty Rate (Poverty Count / Population)
census_pd["Poverty Rate"] = 100 * \
    census_pd["Poverty Count"].astype(
        int) / census_pd["Population"].astype(int)

# Final DataFrame
census_pd = census_pd[["Zipcode", "Population", "Median Age", "Household Income",
                       "Per Capita Income", "Poverty Count", "Poverty Rate"]]

# Visualize
print(len(census_pd))
census_pd.head()

33120

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate
0,00601,17113.0,41.9,14361.0,7493.0,10552.0,61.660726
1,00602,37751.0,42.9,16807.0,9694.0,18653.0,49.410612
2,00603,47081.0,42.1,16049.0,11259.0,23691.0,50.319662
3,00606,6392.0,44.3,12119.0,6093.0,4185.0,65.472466
4,00610,26686.0,42.7,19898.0,10572.0,12204.0,45.731844

In [15]:
#List of Chicago Zips
zips = ['60626',
'60645',
'60660',
'60659',
'60613',
'60640',
'60618',
'60625',
'60614',
'60657',
'60610',
'60642',
'60647',
'60611',
'60654',
'60068',
'60631',
'60630',
'60646',
'60656',
'60714',
'60641',
'60634',
'60706',
'60707',
'60639',
'60622',
'60612',
'60624',
'60651',
'60661',
'60644',
'60804',
'60606',
'60607',
'60608',
'60616',
'60623',
'60632',
'60601',
'60602',
'60603',
'60604',
'60605',
'60609',
'60653',
'60615',
'60621',
'60637',
'60649',
'60619',
'60620',
'60617',
'60628',
'60633',
'60643',
'60827',
'60629',
'60638',
'60636',
'60652',
'60655',
'60007',
'60018',
'60106',
'60131',
'60176']

In [16]:
chicago_zips = census_pd.loc[census_pd['Zipcode'].str.contains('|'.join(zips), na=False)]
chicago_zips

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate
20421,60007,33161.0,43.8,82234.0,41633.0,1198.0,3.612678
20429,60018,30037.0,39.0,64429.0,27653.0,3461.0,11.522456
20459,60068,37433.0,44.9,111740.0,57040.0,1413.0,3.774744
20486,60106,20341.0,36.4,64700.0,29158.0,2078.0,10.215820
20503,60131,17834.0,39.1,64128.0,26242.0,1660.0,9.308063
...,...,...,...,...,...,...,...
20750,60706,23114.0,45.9,68808.0,34236.0,1664.0,7.199100
20751,60707,43093.0,40.5,61718.0,30699.0,3480.0,8.075558
20753,60714,29520.0,48.4,64790.0,32745.0,2609.0,8.838076
20755,60804,82383.0,30.5,49412.0,18500.0,13166.0,15.981452
20757,60827,28483.0,32.3,32329.0,19484.0,8654.0,30.383035

In [10]:
chicago_zips.to_csv("chicago_census_data.csv", encoding="utf-8", index=False)